# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: octokit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # append stats to data/octokit.csv
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/octokit.csv
          columns: open issues,closed issues,open pull requests,closed pull requests,merged pull requests
          "open issues": ${{ fromJson(steps.stats.outputs.data).openIssues }}
          "closed issues": ${{ fromJson(steps.stats.outputs.data).closedIssues }}
          "open pull requests": ${{ fromJson(steps.stats.outputs.data).openPullRequests }}
          "closed pull requests": ${{ fromJson(steps.stats.outputs.data).closedPullRequests }}
          "merged pull requests": ${{ fromJson(steps.stats.outputs.data).mergedPullRequests }}
      - run: |
          chown -R $(whoami) .
          ls
          pwd
          touch new.txt
          echo ${{github.event.head_commit.message}} >> ./new.txt
          echo ${{github.event.head_commit.message}} >> ./README.md
      # push updated file back to main branch
      - run: git config --local user.email "jatinkumar11954@gmail.com"
      - run: git config --local user.name "jatinkumar11954"
      - run: git add .
      - run: git commit -m " updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run a one-line script
        run: |
          chown -R $(whoami) .
          ls
          pwd
          touch new.txt
          echo ${{github.event.head_commit.message}} >> ./new.txt
          echo ${{github.event.head_commit.message}} >> ./README.md
 
      # Runs a set of commands using the runners shell
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: README.md
          contents: |
            echo ${{github.event.head_commit.message}} >> README.md
          write-mode: append
